### ISSUE TITLE
Webpage - Logiin / database

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#10]
Is page 0 (pre login) set to a unique database? or is the database static to 1 database and that database only stores user information

---

Is database information stored client side or serverside?

**Comment by commande** [comment]
Looks like the JDBC static object is persistent across pages, meaning there's a single instance of it in the server. This should mean it can be handled server side.

also, when referring to JDBC I mean the actual JDBC class in the db package.

**Comment by commande** [comment]
also, when referring to JDBC I mean the actual JDBC class in the db package.

**Comment by cheng10** [comment]
Yes. oracle login and the syetem login wil login into a same database account. Ensured by using same  oracle usename and acount using session.
