### ISSUE TITLE
No foreign key restraints on tables

### ISSUE THREAD

**Issue by commande** [C391-Project/RadiologyApp#23]
I've only noticed this, haven't looked at why. But there are don't appear to be foreign key restraints on the table, thus allowing us to create a user without a person or a PACS_IMAGE without a record id. Can we add these to the create table statements? Or are they in there already and not working?

**Comment by Shining-Trapezohedron** [comment]
Probably an oversight on my part I will look into it

**Comment by Shining-Trapezohedron** [comment]
Oh right, This is the supplied setup.sql
I have been working on queries and inserting some data into tables via sql 
I should be finished tonight, I will attempt to test this issue as I peck through it
