### ISSUE TITLE
validate password error

### ISSUE THREAD

**Issue by cheng10** [C391-Project/RadiologyApp#26]
i wrote few lines of code in the login.jp.
However, i encountered some annoying problems.
When i validate integer passwords, it works every time.
However, when it comes to string passwords. i alway fail.
I am pretty confused. And it stops me form writing code about validate the user type.
@lolicatgirls @commande

**Comment by commande** [comment]
@cheng10 Has this issue been resolved? I tested it with the given test cases and it worked fine with a string password.

**Comment by cheng10** [comment]
yes, it is fixed now.
