### ISSUE TITLE
User_Homepage.EditProfile

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#3]
As a user I want to be able to modify my personal information

**Comment by cheng10** [comment]
A user should be able to change their own information about users.password  and person_id, first_name, last_name, address, email, phone which are in the person table.

**Comment by cheng10** [comment]
I don't think it is suitable to implement those functions in the login module. It will be better if we can build EditProfile and EditPassword pages.
