### ISSUE TITLE
Code organization

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#36]
Is it possible to organize our files by type? 
more specifically can we split up all our jsp and html into their own folder heirarchy 

if it makes coding and testing inconvenient don't bother it's just that at the moment its a tad ugly seeing examples and whatnot mixed together

**Comment by commande** [comment]
I've begun organizing my files by type, take a look at WebContent.UserManage and src.servlets for examples of what I'm working on.
