### ISSUE TITLE
User_Homepage.EditPassword

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#4]
As a user I want to be able to modify my password

**Comment by cheng10** [comment]
Should be include in a user's profile(setting) page. Not suitable to be implement in the login module.From my understanding, login module should focus on authenticating whether a user has permission to access to the website and what kind of information he can get access to.

**Comment by cheng10** [comment]
Hence, i changed title to EditPassword.
We should implement a EditPassword page. Therefore, a user can change his password AFTER he logged in successfully.

**Comment by cheng10** [comment]
Done.
