### ISSUE TITLE
How check whether  an user has logged in the database

### ISSUE THREAD

**Issue by cheng10** [C391-Project/RadiologyApp#43]
For the loginservlet.java, i want to check whether the user has logged in the database.
like this:
 if(session.getAttribute("dbusername")==null)
            {
                session.setAttribute("error", "Please login to the database first.");
                response.setHeader("Refresh", "0; URL=oracle-login");
            }
            else
            {
                DBusername=session.getAttribute("dbusername").toString();
                DBpassword=session.getAttribute("dbpassword").toString();
                isConnectingFromLab=(Boolean)session.getAttribute("dblab");
            }

if it works, i think i will be redirected to the oracle-login, with the warning of "Please login to the database first."

However, this part of code never runs a single time.

Everytime, when i try to login without logged into the database before, i will be staying at the login.jsp with the warning "Invalid conInvalid combination of username, password!"

I think i need your help.
@lolicatgirls @commande

**Comment by commande** [comment]
## Oracle login servlet does not save the login info to the session. If you need to check db connection do this:

DataSource ds = new DataSource();

If (ds.isNotConfigured()) {
  // redirect

## }

Hope that helps

**Comment by cheng10** [comment]
Thanks a lot, it works.

However, i did find a fraction of code stores the db info into the session.

Is there any way to check whether one attribute in the session is null?

OracleLogin.java
// Store database login info to the session in case later needed.
        session.setAttribute("dbusername", request.getParameter("username"));
        session.setAttribute("dbpassword", request.getParameter("password"));
        session.setAttribute("dblab", 
                (request.getParameter("labconnection") != null && request.getParameter("labconnection").equals("yes"))
        );

**Comment by commande** [comment]
Right, I forgot I left that in.

Can you use:

Session.getAttribute("attribute") == null
