### ISSUE TITLE
Friday meeting time

### ISSUE THREAD

**Issue by cheng10** [C391-Project/RadiologyApp#44]
Hi James & Brett:

Are we planning to meet in friday? if so, what is the time and place?

@commande @lolicatgirls

**Comment by Shining-Trapezohedron** [comment]
I'm not 100% sure but I do think I remember Brett saying he wasn't available today

**Comment by cheng10** [comment]
No worries. If we encounter any problems, we can communicate with email
though. Have a "Good Friday".

**Comment by commande** [comment]
Hey guys! I'm working on the report as we speak and am available tomorrow from 12-6pm and plan on cranking this thing out. 

By tomorrow I will have finished all the documentation for my end including code, report and user manual for the upload and user management module and I plan on building in the mechanism for displaying the user manual tomorrow afternoon. Shouldn't be difficult at all.
