### ISSUE TITLE
Project Demo in Lab on Wednesday April 8

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#46]
http://doodle.com/8h7aa39vtgqiwf9r#table

We are group 11

**Comment by Shining-Trapezohedron** [comment]
@commande 
@cheng10 
Just going to throw out a reminder or something I guess
Doesn't hurt, I suppose

**Comment by cheng10** [comment]
Thanks, James.
See you guys on Wednesday 2 p.m at csc 2-19.
