### ISSUE TITLE
UserType, User_Homepage, Admin_Homepage

### ISSUE THREAD

**Issue by Shining-Trapezohedron** [C391-Project/RadiologyApp#5]
As a user I want to be able to view my account type, and view my privileges

**Comment by cheng10** [comment]
Sure. I will make a drop-list on the login page, so a user can choose from login as a common user or admin.
After a user's successful  login, the webpage will turn to user's homepage or admin's homepage, where he can edit his profile(in the user's homepage) or manage users' activities(in the admin homepage).

**Comment by commande** [comment]
Not sure this is right approach. My understanding is that a user can only be one "class" of user at a time. The login should only require name and password and the system will retrieve which user class they are and grant the relevant privileges.

**Comment by cheng10** [comment]
Your understanding is pretty reasonable.

**Comment by cheng10** [comment]
Done.
